include:
    # Metadata shared my many jobs
    - local: .gitlab/rules.yml
    - local: .gitlab/artifacts.yml
    - local: .gitlab/doxygen.yml

    # OS builds.
    - local: .gitlab/os-windows.yml

stages:
    - build
    - test
    - deploy

################################################################################
# Job declarations
#
# Each job must pull in each of the following keys:
#
#   - a "base image"
#   - a build script
#   - tags for the jobs
#   - rules for when to run the job
#
# Additionally, jobs may also contain:
#
#   - artifacts
#   - dependency/needs jobs for required jobs
################################################################################

pages:
    extends:
        - .doxygen_build
        - .doxygen_on_mirror

# Windows

## Build and test

windows-vs2022-ninja:build:
    extends:
        - .windows_vs2022_ninja
        - .cmake_build_windows
        - .cmake_build_artifacts
        - .windows_builder_tags
        - .run_manually

windows-vs2022-ninja:test:
    extends:
        - .windows_vs2022_ninja
        - .cmake_test_windows
        - .cmake_test_artifacts
        - .windows_builder_tags
        - .run_dependent
    dependencies:
        - windows-vs2022-ninja:build
    needs:
        - windows-vs2022-ninja:build
